"""Initial schema — all 13 tables.

This coarse initial revision builds the full schema from the SQLAlchemy
metadata so `alembic upgrade head` produces every table on an empty database
(spec SC-003). Subsequent migrations should be granular and autogenerated
(`alembic revision --autogenerate`).

Revision ID: 0001
Revises:
Create Date: 2026-06-07
"""

from __future__ import annotations

from alembic import op

from booking_agent.db import models  # noqa: F401  (register models on Base)
from booking_agent.db.base import Base

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
